title: "Lehi Sanchez"
domain: lehisanchez.com
url: "https://lehisanchez.com"
baseurl: ""

source: _site
destination: docs
disable_disk_cache: true

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false

include:
  - CNAME
keep_files:
  - CNAME

social:
  name: Lehi Sanchez
  links:
    - https://github.com/lehisanchez
